# Importing Dependencies

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

make_block generator datas

# Loading Dataset and Preprocessing

In [6]:
X, Y = make_blobs(n_samples=5000, centers=3, cluster_std=4, random_state=42) # Three clustures

In [7]:
df = pd.DataFrame(X, columns=['Feature_1', 'Feature_2'])

In [8]:
df

      Feature_1  Feature_2
0      0.696664   0.836549
1     -0.329107  -2.529179
2     -5.899733   6.405931
3      0.227141   5.255384
4     -8.729759  -5.329390
...         ...        ...
4995   3.787994  -6.491486
4996  -3.914855  15.267940
4997   4.560384   1.544111
4998  -3.998025  13.369281
4999   4.848913  -2.269251

[5000 rows x 2 columns]

In [9]:
df.head()

   Feature_1  Feature_2
0   0.696664   0.836549
1  -0.329107  -2.529179
2  -5.899733   6.405931
3   0.227141   5.255384
4  -8.729759  -5.329390