**Pandas Library:**


 Useful for Data Processing and Analysis

**Pandas Data Frame:**

 Pandas DataFrame is two-dimensional tabular data structure with labeled axes (rows x cols)

In [15]:
# Importing the pandas library

import pandas as pd
import numpy as np

# Creating a Pandas DataFrame

In [16]:

# Importing the boston House price data
from sklearn.datasets import fetch_openml

# Load the Boston Housing dataset from OpenML
boston_dataset = fetch_openml(name='boston', version=1, as_frame=True)

print(boston_dataset)

{'data':         CRIM    ZN  INDUS CHAS    NOX     RM   AGE     DIS RAD    TAX  \
0    0.00632  18.0   2.31    0  0.538  6.575  65.2  4.0900   1  296.0
1    0.02731   0.0   7.07    0  0.469  6.421  78.9  4.9671   2  242.0
2    0.02729   0.0   7.07    0  0.469  7.185  61.1  4.9671   2  242.0
3    0.03237   0.0   2.18    0  0.458  6.998  45.8  6.0622   3  222.0
4    0.06905   0.0   2.18    0  0.458  7.147  54.2  6.0622   3  222.0
..       ...   ...    ...  ...    ...    ...   ...     ...  ..    ...
501  0.06263   0.0  11.93    0  0.573  6.593  69.1  2.4786   1  273.0
502  0.04527   0.0  11.93    0  0.573  6.120  76.7  2.2875   1  273.0
503  0.06076   0.0  11.93    0  0.573  6.976  91.0  2.1675   1  273.0
504  0.10959   0.0  11.93    0  0.573  6.794  89.3  2.3889   1  273.0
505  0.04741   0.0  11.93    0  0.573  6.030  80.8  2.5050   1  273.0

     PTRATIO       B  LSTAT
0       15.3  396.90   4.98
1       17.8  396.90   9.14
2       17.8  392.83   4.03
3       18.7  394.63   2.94
4       18.7  396.90   5.33
..       ...     ...    ...
501     21.0  391.99   9.67
502     21.0  396.90   9.08
503     21.0  396.90   5.64
504     21.0  393.45   6.48
505     21.0  396.90   7.88

[506 rows x 13 columns], 'target': 0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ...
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: MEDV, Length: 506, dtype: float64, 'frame':         CRIM    ZN  INDUS CHAS    NOX     RM   AGE     DIS RAD    TAX  \
0    0.00632  18.0   2.31    0  0.538  6.575  65.2  4.0900   1  296.0
1    0.02731   0.0   7.07    0  0.469  6.421  78.9  4.9671   2  242.0
2    0.02729   0.0   7.07    0  0.469  7.185  61.1  4.9671   2  242.0
3    0.03237   0.0   2.18    0  0.458  6.998  45.8  6.0622   3  222.0
4    0.06905   0.0   2.18    0  0.458  7.147  54.2  6.0622   3  222.0
..       ...   ...    ...  ...    ...    ...   ...     ...  ..    ...
501  0.06263   0.0  11.93    0  0.573  6.593  69.1  2.4786   1  273.0
502  0.04527   0.0  11.93    0  0.573  6.120  76.7  2.2875   1  273.0
503  0.06076   0.0  11.93    0  0.573  6.976  91.0  2.1675   1  273.0
504  0.10959   0.0  11.93    0  0.573  6.794  89.3  2.3889   1  273.0
505  0.04741   0.0  11.93    0  0.573  6.030  80.8  2.5050   1  273.0

     PTRATIO       B  LSTAT  MEDV
0       15.3  396.90   4.98  24.0
1       17.8  396.90   9.14  21.6
2       17.8  392.83   4.03  34.7
3       18.7  394.63   2.94  33.4
4       18.7  396.90   5.33  36.2
..       ...     ...    ...   ...
501     21.0  391.99   9.67  22.4
502     21.0  396.90   9.08  20.6
503     21.0  396.90   5.64  23.9
504     21.0  393.45   6.48  22.0
505     21.0  396.90   7.88  11.9

[506 rows x 14 columns], 'categories': None, 'feature_names': ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT'], 'target_names': ['MEDV'], 'DESCR': "**Author**:   \n**Source**: Unknown - Date unknown  \n**Please cite**:   \n\nThe Boston house-price data of Harrison, D. and Rubinfeld, D.L. 'Hedonic\nprices and the demand for clean air', J. Environ. Economics & Management,\nvol.5, 81-102, 1978.   Used in Belsley, Kuh & Welsch, 'Regression diagnostics\n...', Wiley, 1980.   N.B. Various transformations are used in the table on\npages 244-261 of the latter.\nVariables in order:\nCRIM     per capita crime rate by town\nZN       proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS    proportion of non-retail business acres per town\nCHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\nNOX      nitric oxides concentration (parts per 10 million)\nRM       average number of rooms per dwelling\nAGE      proportion of owner-occupied units built prior to 1940\nDIS      weighted distances to five Boston employment centres\nRAD      index of accessibility to radial highways\nTAX      full-value property-tax rate per $10,000\nPTRATIO  pupil-teacher ratio by town\nB        1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT    % lower status of the population\nMEDV     Median value of owner-occupied homes in $1000's\n\n\nInformation about the dataset\nCLASSTYPE: numeric\nCLASSINDEX: last\n\nDownloaded from openml.org.", 'details': {'id': '531', 'name': 'boston', 'version': '1', 'description_version': '1', 'format': 'ARFF', 'creator': ['D. and Rubinfeld', "D.L. 'Hedonic"], 'collection_date': '1978', 'upload_date': '2014-09-29T00:08:07', 'language': 'English', 'licence': 'Public', 'url': 'https://api.openml.org/data/v1/download/52643/boston.arff', 'parquet_url': 'https://data.openml.org/datasets/0000/0531/dataset_531.pq', 'file_id': '52643', 'default_target_attribute': 'MEDV', 'tag': ['Data Science', 'Housing Economics', 'Kaggle', 'OpenML-Reg19', 'study_130', 'Urban Studies'], 'visibility': 'public', 'minio_url': 'https://data.openml.org/datasets/0000/0531/dataset_531.pq', 'status': 'active', 'processing_date': '2020-11-20 20:16:37', 'md5_checksum': 'cdd361fb886627eaa80c92f90d0610cc'}, 'url': 'https://www.openml.org/d/531'}

In [17]:
type(boston_dataset)

sklearn.utils._bunch.Bunch

In [18]:
# Pandas DataFrame

boston_df = pd.DataFrame(boston_dataset.data, columns=boston_dataset.feature_names)

In [19]:
type(boston_df)

pandas.core.frame.DataFrame

In [20]:
print(boston_df)

        CRIM    ZN  INDUS CHAS    NOX     RM   AGE     DIS RAD    TAX  \
0    0.00632  18.0   2.31    0  0.538  6.575  65.2  4.0900   1  296.0
1    0.02731   0.0   7.07    0  0.469  6.421  78.9  4.9671   2  242.0
2    0.02729   0.0   7.07    0  0.469  7.185  61.1  4.9671   2  242.0
3    0.03237   0.0   2.18    0  0.458  6.998  45.8  6.0622   3  222.0
4    0.06905   0.0   2.18    0  0.458  7.147  54.2  6.0622   3  222.0
..       ...   ...    ...  ...    ...    ...   ...     ...  ..    ...
501  0.06263   0.0  11.93    0  0.573  6.593  69.1  2.4786   1  273.0
502  0.04527   0.0  11.93    0  0.573  6.120  76.7  2.2875   1  273.0
503  0.06076   0.0  11.93    0  0.573  6.976  91.0  2.1675   1  273.0
504  0.10959   0.0  11.93    0  0.573  6.794  89.3  2.3889   1  273.0
505  0.04741   0.0  11.93    0  0.573  6.030  80.8  2.5050   1  273.0

     PTRATIO       B  LSTAT
0       15.3  396.90   4.98
1       17.8  396.90   9.14
2       17.8  392.83   4.03
3       18.7  394.63   2.94
4       18.7  396.90   5.33
..       ...     ...    ...
501     21.0  391.99   9.67
502     21.0  396.90   9.08
503     21.0  396.90   5.64
504     21.0  393.45   6.48
505     21.0  396.90   7.88

[506 rows x 13 columns]

In [21]:
boston_df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33

In [22]:
boston_df.shape

(506, 13)

# Importing the data from csv file to a pandas DataFrame

In [23]:
# CSV file to pandas DataFrame

diabetes_df = pd.read_csv("diabetes.csv")

In [24]:
type(diabetes_df)

pandas.core.frame.DataFrame

In [25]:
diabetes_df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [26]:
diabetes_df.shape

(768, 9)

# Loading the data from Excel file to a pandas DataFrame

In [27]:
# Excel file to pandas DataFrame

olympics_df = pd.read_excel("olympics-data.xlsx")

In [28]:
type(olympics_df)

pandas.core.frame.DataFrame

In [29]:
olympics_df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

# Exporting a DataFrame to CSV

In [30]:
boston_df.to_csv("Boston.csv")

# Exprting a DataFrame to Excel

In [31]:
boston_df.to_excel("Boston.xlsx")

In [32]:
# Creating a DataFrame with random variable

random_df = pd.DataFrame(np.random.randint(10,100, size=(10,20)))

In [33]:
random_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,35,39,19,31,46,97,38,54,21,64,92,21,62,39,37,98,55,91,18,67
1,41,33,92,25,76,76,65,35,11,39,99,83,66,48,24,67,20,32,46,48
2,69,81,80,11,55,58,79,92,73,91,73,96,19,96,43,36,36,82,40,30
3,81,90,53,80,16,14,90,10,89,74,67,32,10,78,97,87,28,83,90,59
4,58,89,47,78,31,53,50,70,65,42,53,23,17,18,58,85,84,32,55,64

In [34]:
random_df.shape

(10, 20)

In [35]:
random_df = pd.DataFrame(np.random.rand(10,100))
random_df.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.588693,0.117976,0.496396,0.184278,0.160639,0.057589,0.533510,0.095559,0.249054,0.387046,...,0.761455,0.116905,0.599183,0.833568,0.181851,0.549337,0.732552,0.104374,0.438345,0.768436
1,0.298876,0.884199,0.246093,0.837754,0.137031,0.160955,0.666369,0.420332,0.171371,0.614294,...,0.849140,0.858788,0.234188,0.597848,0.089102,0.929184,0.255410,0.677999,0.622714,0.798610
2,0.937925,0.515888,0.604957,0.055904,0.324960,0.321621,0.592518,0.587209,0.609487,0.919550,...,0.311354,0.453410,0.598735,0.792216,0.048968,0.567899,0.894937,0.798187,0.933042,0.424302
3,0.719559,0.902034,0.297992,0.382364,0.314123,0.712157,0.264304,0.404823,0.213869,0.701709,...,0.467758,0.090020,0.192949,0.794526,0.864405,0.920671,0.682017,0.147339,0.664985,0.397048
4,0.292068,0.230445,0.933779,0.297955,0.372346,0.829588,0.010836,0.902249,0.852936,0.485934,...,0.027155,0.091642,0.016904,0.101988,0.234080,0.580327,0.713525,0.166763,0.111935,0.327485

In [36]:
random_df.shape

(10, 100)

# Inspecting a DataFrame

In [37]:
# Finding number of rows and cols

boston_df.shape

(506, 13)

In [43]:
# Print fist five rows

boston_df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33

In [42]:
# Print Last five rows

boston_df.tail()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88

In [44]:
# Information about the DataFrame

boston_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    category
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    category
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
dtypes: category(2), float64(11)
memory usage: 45.1 KB

In [46]:
# Finding the number of missing values

boston_df.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
dtype: int64

In [47]:
diabetes_df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [53]:
# Counting the values based on the labels

diabetes_df.value_counts('Outcome')

Outcome
0    500
1    268
Name: count, dtype: int64

In [55]:
# Group the values based on the mean

diabetes_df.groupby('Outcome').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.298000,109.980000,68.184000,19.664000,68.792000,30.304200,0.429734,31.190000
1,4.865672,141.257463,70.824627,22.164179,100.335821,35.142537,0.550500,37.067164

# Statistical Measures

In [56]:
# Count or number of values

boston_df.count()

CRIM       506
ZN         506
INDUS      506
CHAS       506
NOX        506
RM         506
AGE        506
DIS        506
RAD        506
TAX        506
PTRATIO    506
B          506
LSTAT      506
dtype: int64

In [60]:
# Mean value - col wise (excluding categorical columns)
boston_df.select_dtypes(include=[np.number]).mean()

CRIM         3.613524
ZN          11.363636
INDUS       11.136779
NOX          0.554695
RM           6.284634
AGE         68.574901
DIS          3.795043
TAX        408.237154
PTRATIO     18.455534
B          356.674032
LSTAT       12.653063
dtype: float64

In [62]:
# Standard Deviation col wise

boston_df.select_dtypes(include=[np.number]).std()

CRIM         8.601545
ZN          23.322453
INDUS        6.860353
NOX          0.115878
RM           0.702617
AGE         28.148861
DIS          2.105710
TAX        168.537116
PTRATIO      2.164946
B           91.294864
LSTAT        7.141062
dtype: float64

In [64]:
# Minimum values in each col

boston_df.select_dtypes(include=[np.number]).min()

CRIM         0.00632
ZN           0.00000
INDUS        0.46000
NOX          0.38500
RM           3.56100
AGE          2.90000
DIS          1.12960
TAX        187.00000
PTRATIO     12.60000
B            0.32000
LSTAT        1.73000
dtype: float64

In [65]:
# Maximum values in each col

boston_df.select_dtypes(include=[np.number]).max()

CRIM        88.9762
ZN         100.0000
INDUS       27.7400
NOX          0.8710
RM           8.7800
AGE        100.0000
DIS         12.1265
TAX        711.0000
PTRATIO     22.0000
B          396.9000
LSTAT       37.9700
dtype: float64

In [66]:
# All satistical measures in the DataFrame

boston_df.describe()

,CRIM,ZN,INDUS,NOX,RM,AGE,DIS,TAX,PTRATIO,B,LSTAT
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.554695,6.284634,68.574901,3.795043,408.237154,18.455534,356.674032,12.653063
std,8.601545,23.322453,6.860353,0.115878,0.702617,28.148861,2.105710,168.537116,2.164946,91.294864,7.141062
min,0.006320,0.000000,0.460000,0.385000,3.561000,2.900000,1.129600,187.000000,12.600000,0.320000,1.730000
25%,0.082045,0.000000,5.190000,0.449000,5.885500,45.025000,2.100175,279.000000,17.400000,375.377500,6.950000
50%,0.256510,0.000000,9.690000,0.538000,6.208500,77.500000,3.207450,330.000000,19.050000,391.440000,11.360000
75%,3.677083,12.500000,18.100000,0.624000,6.623500,94.075000,5.188425,666.000000,20.200000,396.225000,16.955000
max,88.976200,100.000000,27.740000,0.871000,8.780000,100.000000,12.126500,711.000000,22.000000,396.900000,37.970000

# Manupulating a DataFrame

In [ ]:
# Adding a col to DataFrame