# Importing Dependencies

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from sklearn.metrics import r2_score
import seaborn as sns

# Data Collection and Preprocessing

In [4]:
# Loading data

calorie_data = pd.read_csv('calories.csv')
exercise_data = pd.read_csv('exercise.csv')

In [5]:
calorie_data.head()

    User_ID  Calories
0  14733363     231.0
1  14861698      66.0
2  11179863      26.0
3  16180408      71.0
4  17771927      35.0

In [6]:
exercise_data.head()

    User_ID  Gender  Age  Height  Weight  Duration  Heart_Rate  Body_Temp
0  14733363    male   68   190.0    94.0      29.0       105.0       40.8
1  14861698  female   20   166.0    60.0      14.0        94.0       40.3
2  11179863    male   69   179.0    79.0       5.0        88.0       38.7
3  16180408  female   34   179.0    71.0      13.0       100.0       40.5
4  17771927  female   27   154.0    58.0      10.0        81.0       39.8

Combining Two Data Frames

In [9]:
calorie_data = pd.concat([exercise_data, calorie_data['Calories']], axis=1)

In [10]:
# First five rows

calorie_data.head()

    User_ID  Gender  Age  Height  ...  Duration  Heart_Rate  Body_Temp  Calories
0  14733363    male   68   190.0  ...      29.0       105.0       40.8     231.0
1  14861698  female   20   166.0  ...      14.0        94.0       40.3      66.0
2  11179863    male   69   179.0  ...       5.0        88.0       38.7      26.0
3  16180408  female   34   179.0  ...      13.0       100.0       40.5      71.0
4  17771927  female   27   154.0  ...      10.0        81.0       39.8      35.0

[5 rows x 9 columns]

In [11]:
# No of rows and cols

calorie_data.shape

(15000, 9)

In [12]:
calorie_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   User_ID     15000 non-null  int64
 1   Gender      15000 non-null  object
 2   Age         15000 non-null  int64
 3   Height      15000 non-null  float64
 4   Weight      15000 non-null  float64
 5   Duration    15000 non-null  float64
 6   Heart_Rate  15000 non-null  float64
 7   Body_Temp   15000 non-null  float64
 8   Calories    15000 non-null  float64
dtypes: float64(6), int64(2), object(1)
memory usage: 1.0+ MB

In [13]:
# Get statistical details

calorie_data.describe()

            User_ID           Age  ...     Body_Temp      Calories
count  1.500000e+04  15000.000000  ...  15000.000000  15000.000000
mean   1.497736e+07     42.789800  ...     40.025453     89.539533
std    2.872851e+06     16.980264  ...      0.779230     62.456978
min    1.000116e+07     20.000000  ...     37.100000      1.000000
25%    1.247419e+07     28.000000  ...     39.600000     35.000000
50%    1.499728e+07     39.000000  ...     40.200000     79.000000
75%    1.744928e+07     56.000000  ...     40.600000    138.000000
max    1.999965e+07     79.000000  ...     41.500000    314.000000

[8 rows x 8 columns]