# Importing Dependencies

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import cross_val_score

In [2]:
# Importing Models

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

# Dataset:

Heart Disease Dataset

In [3]:
heart_data = pd.read_csv('heart.csv')

# Data Preprocessing

In [4]:
# First Five Rows

heart_data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [5]:
# Last five rows

heart_data.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [6]:
heart_data.shape

(303, 14)

In [7]:
# Checking missing values

heart_data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [8]:
# Checking Distribution of Target Variable

heart_data['target'].value_counts()

target
1    165
0    138
Name: count, dtype: int64

- 1 --> Defective Heart

- 0 --> Healthy Heart

# Splitting Feature and Target

In [9]:
X = heart_data.drop(columns='target', axis=1)
Y = heart_data['target']

In [10]:
print(X)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
1     37    1   2       130   250    0        1      187      0      3.5
2     41    0   1       130   204    0        0      172      0      1.4
3     56    1   1       120   236    0        1      178      0      0.8
4     57    0   0       120   354    0        1      163      1      0.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
298   57    0   0       140   241    0        1      123      1      0.2
299   45    1   3       110   264    0        1      132      0      1.2
300   68    1   0       144   193    1        1      141      0      3.4
301   57    1   0       130   131    0        1      115      1      1.2
302   57    0   1       130   236    0        0      174      0      0.0

     slope  ca  thal
0        0   0     1
1        0   0     2
2        2   0     2
3        2   0     2
4        2   0     2
..     ...  ..   ...
298      1   0     3
299      1   0     3
300      1   2     3
301      1   1     3
302      1   1     2

[303 rows x 13 columns]

In [11]:
print(Y)

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [12]:
X = np.asarray(X)
Y = np.asarray(Y)

# Model Selection

1. Comparing the models with default hyperparameter values using cross validatoin

In [13]:
models = [LogisticRegression(max_iter=1000), SVC(kernel='linear'), KNeighborsClassifier(), RandomForestClassifier(random_state=0)]

In [14]:
def compare_models_cross_validation():

    for model in models:
        cv_score = cross_val_score(model, X, Y, cv = 5)
        mean_accuracy = sum(cv_score)/len(cv_score)
        mean_accuracy = mean_accuracy * 100
        mean_accuracy = round(mean_accuracy, 2)


        print("Cross Validation Accuracy of the ", model,"is = ", cv_score)
        print("Accuracy score of the ", model,"is = ", mean_accuracy)
        print("***********************************")

In [15]:
compare_models_cross_validation()

Cross Validation Accuracy of the  LogisticRegression(max_iter=1000) is =  [0.80327869 0.86885246 0.85245902 0.86666667 0.75      ]
Accuracy score of the  LogisticRegression(max_iter=1000) is =  82.83
***********************************
Cross Validation Accuracy of the  SVC(kernel='linear') is =  [0.81967213 0.8852459  0.80327869 0.86666667 0.76666667]
Accuracy score of the  SVC(kernel='linear') is =  82.83
***********************************
Cross Validation Accuracy of the  KNeighborsClassifier() is =  [0.60655738 0.6557377  0.57377049 0.73333333 0.65      ]
Accuracy score of the  KNeighborsClassifier() is =  64.39
***********************************
Cross Validation Accuracy of the  RandomForestClassifier(random_state=0) is =  [0.85245902 0.90163934 0.81967213 0.81666667 0.8       ]
Accuracy score of the  RandomForestClassifier(random_state=0) is =  83.81
***********************************

Inference: For the Heart Disease dataset, Random Forest Classifier has the Highest accuracy value with default hyperparameter values

2. Comparing the models with differnt hyperparameters values using GridSearchCV

In [16]:
models_list = [LogisticRegression(max_iter=1000), SVC(kernel='linear'), KNeighborsClassifier(), RandomForestClassifier(random_state=0)]

In [17]:
# Creating a directory that contain hyperparamer values for the above mentioned model

model_hyperparameters = {
    'log_reg_hyperparameter':{
        'C':[1, 5, 10, 20]
    },

    'svc_hyperparameter':{
        'kernel':['linear', 'poly', 'rbf', 'sigmoid'],
        'C':[1, 5, 10, 20]
    },

    'KNN_hyperparameter':{
        'n_neighbors':[3, 5, 10]
    },

    'random_forest_hyperparameter':{
        'n_estimators':[10,20, 50, 100]
    }
}

In [18]:
type(model_hyperparameters)

dict

In [19]:
print(model_hyperparameters.keys())

dict_keys(['log_reg_hyperparameter', 'svc_hyperparameter', 'KNN_hyperparameter', 'random_forest_hyperparameter'])

In [20]:
model_hyperparameters['log_reg_hyperparameter']

{'C': [1, 5, 10, 20]}

In [21]:
model_keys = list(model_hyperparameters.keys())
print(model_keys)

['log_reg_hyperparameter', 'svc_hyperparameter', 'KNN_hyperparameter', 'random_forest_hyperparameter']

In [22]:
model_keys[0]

'log_reg_hyperparameter'

In [23]:
model_hyperparameters[model_keys[0]]

{'C': [1, 5, 10, 20]}

# Applying GridSearchCV

In [38]:
def ModelSelection(list_of_models, hyperparameters_dictionary):

    result = []

    i = 0

    for model in list_of_models:
        key=model_keys[i]
        params = hyperparameters_dictionary[key]

        i = i+1

        print(model)
        print(params)
        print("**************************")

        classifier = GridSearchCV(model, params, cv = 5)

        # fitting the data in classifer

        classifier.fit(X, Y)

        result.append({
            'model_used':model,
            'highest_score':classifier.best_score_,
            'best_hyperparameters': classifier.best_params_
        })


    result_dataframe = pd.DataFrame(result, columns=['model_used', 'highest_score', 'best_hyperparameters'])

    return result_dataframe

In [39]:
ModelSelection(models_list, model_hyperparameters)

LogisticRegression(max_iter=1000)
{'C': [1, 5, 10, 20]}
**************************

d:\# My Learning\Coding\Machine-Learning-Tutorial\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\# My Learning\Coding\Machine-Learning-Tutorial\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\# My Learning\Coding\Machine-Learning-Tutorial\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\# My Learning\Coding\Machine-Learning-Tutorial\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\# My Learning\Coding\Machine-Learning-Tutorial\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\# My Learning\Coding\Machine-Learning-Tutorial\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\# My Learning\Coding\Machine-Learning-Tutorial\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\# My Learning\Coding\Machine-Learning-Tutorial\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

SVC(kernel='linear')
{'kernel': ['linear', 'poly', 'rbf', 'sigmoid'], 'C': [1, 5, 10, 20]}
**************************
KNeighborsClassifier()
{'n_neighbors': [3, 5, 10]}
**************************
RandomForestClassifier(random_state=0)
{'n_estimators': [10, 20, 50, 100]}
**************************

,model_used,highest_score,best_hyperparameters
0,LogisticRegression(max_iter=1000),0.831585,{'C': 20}
1,SVC(kernel='linear'),0.828306,"{'C': 1, 'kernel': 'linear'}"
2,KNeighborsClassifier(),0.643880,{'n_neighbors': 5}
3,RandomForestClassifier(random_state=0),0.838087,{'n_estimators': 100}

Random Forest Classifier with n_estimators = 100 has the highest accuracy